if game.PlaceId == 9791603388 then --Underground War 2.0
  loadstring(game:HttpGet("https://raw.githubusercontent.com/Darkmoonxhubscript/Scripts/refs/heads/main/Underground%20War%202.0%20%5BNUKE%5D"))()
elseif game.PlaceId == 4924922222 then --BrookHaven RP
  loadstring(game:HttpGet("https://raw.githubusercontent.com/Darkmoonxhubscript/Scripts/refs/heads/main/BrookHaven%20RP"))()
elseif game.PlaceId == 205224386 then --Hideseek Extreme
loadstring(game:HttpGet("https://raw.githubusercontent.com/Darkmoonxhubscript/Scripts/refs/heads/main/HideSeekExtreme"))()
elseif game.PlaceId == 7577073048 or game.PlaceId == 7540891731 then --Red Light, Green Light
loadstring(game:HttpGet("https://raw.githubusercontent.com/Darkmoonxhubscript/Scripts/refs/heads/main/RLGL"))()
  end
