if game.PlaceId == 4924922222 then --BrookHaven RP
  loadstring(game:HttpGet("https://raw.githubusercontent.com/Darkmoonxhubscript/Scripts/refs/heads/main/BrookHaven%20RP"))()
elseif game.PlaceId == 205224386 then --Hideseek Extreme
loadstring(game:HttpGet("https://raw.githubusercontent.com/Darkmoonxhubscript/Scripts/refs/heads/main/HideSeekExtreme"))()
elseif game.PlaceId == 0 or game.PlaceId == 1 then --Dead Rails
loadstring(game:HttpGet("https://raw.githubusercontent.com/Darkmoonxhubscript/Scripts/refs/heads/main/DeadRails.luau"))()
  end
