if game.PlaceId == 4924922222 then --BrookHaven RP
  loadstring(game:HttpGet("https://raw.githubusercontent.com/Darkmoonxhubscript/Scripts/refs/heads/main/BrookHaven%20RP"))()
elseif game.PlaceId == 205224386 then --Hideseek Extreme
loadstring(game:HttpGet("https://raw.githubusercontent.com/Darkmoonxhubscript/Scripts/refs/heads/main/HideSeekExtreme"))()
elseif game.PlaceId == 116495829188952 or game.PlaceId == 70876832253163 then --Dead Rails
loadstring(game:HttpGet("https://raw.githubusercontent.com/Darkmoonxhubscript/Scripts/refs/heads/main/DeadRails.luau"))()
  end
